### ISSUE TITLE
Bad callback errors occurred while detecting the lane, traffic sign, traffic light, etc.

### ISSUE THREAD

**Issue by wsung1** [ROBOTIS-GIT/turtlebot3_autorace#21] opened 2018-07-23 12:01 UTC
Hi, ROBOTIS!
I'd thank you guys for such a great challenge you made!
Now I'm working on turtlebot3_autorace packages with following their tutorials (http://emanual.robotis.com/docs/en/platform/turtlebot3/autonomous_driving).
Nothing went wrong up to Tutorials: 4. Calibration.
However, from Tutorials: 5. Missions I've bumped into bad callback errors that look alike as follows.

5.1. Lane Detection
![image](https://user-images.githubusercontent.com/26803880/43074922-f1fc2500-8eb9-11e8-8e05-2da33b6a9211.png)

5.2. Traffic Sign
![image](https://user-images.githubusercontent.com/26803880/43074944-0771f8c4-8eba-11e8-9fc3-cb24a9eaf1d8.png)

5.3. Traffic Light
![image](https://user-images.githubusercontent.com/26803880/43074954-0f4cc6dc-8eba-11e8-9ad7-8529870a2fdd.png)

5.4. Parking Lot
![image](https://user-images.githubusercontent.com/26803880/43074961-1572df92-8eba-11e8-8bcd-68a26aabb9a3.png)

Do they mean that the callback function is not called because the message doesn't arrive at?
Please advise me how to approach this problem.
Thank you in advance!

**Comment by kijongGil** [comment] 2018-07-24 07:05
Hi @wsung1 :)
The problem is that the variable declaration position is incorrect. We will update this solve.
But if you want to solve right now, move 'self.counter = 1' on line 59 to line 38 for example in detect_lane. 'self.cvBridge = CvBridge()' is same. 
This issue is the part you found, so if you do a Pull Request we will get your PR. Do you want a PR? Or are we going to fix it? :)

Thanks,
Gilbert.

**Comment by wsung1** [comment] 2018-07-24 08:18
안녕하세요, 길버트님,
저는 조선대학교 기계시스템미래자동차공학부 성우석 교수입니다.
코드 수정 관련해서 전화통화 잠시 가능할지요?
감사합니다 :)

2018년 7월 24일 (화) 16:05, Gilbert <notifications@github.com>님이 작성:

**Comment by Jieul** [comment] 2018-07-24 08:43
Hello, Gilbert.
I'm trying to your answer but I have a problem. In detect_lane.py, 
line 59 is 'self.sub_image_original = rospy.Subscriber('/detect/image_input', Image, self.cbFindLane, queue_size = 1)' 
and line 38 is 'self.lightness_white_h = rospy.get_param("~detect/lane/white/lightness_h", 255)'.
'self.counter = 1' on line 88. Where should I move 'self.counter = 1'?
Or did you mention another node?

**Comment by wsung1** [comment] 2018-07-24 23:55
Hi, @kijongGil,
I don't know why but the line number you mentioned mismatches with my detect_lane.py.
What about if you attach your detect_lane.py so that we could fix the code right away.
The regional competition is just around the corner, please help us move forward, @kijongGil :)

**Comment by kijongGil** [comment] 2018-07-25 01:05
I'm sorry for the confusion.
I said the line 38 and 59 are about detect_sign, In the case of detect_lane, self.counter = 1 is on line 88, move to 53 line.
It is an error that is referenced before the self.counter is define.

**Comment by Jieul** [comment] 2018-07-25 02:07
I changed detect_sign, detect_lane as your comment, but I'm still get the same error. Do you have any other solution to recommend?

Thanks, @kijongGil

**Comment by Jieul** [comment] 2018-07-25 04:18
The /catkin_ws/src/turtlebot3/turtlebot3_description/urdf/turtlebot3_burger_for_autorace.gazebo.xacro/ on [Remote PC], [SBC] was changed. Then I calibrated some camera matrix param(intrinsic, extrinsic) and each detection param(HSV) according to your comment. Each detection can be checked in rqt and it looks like it's working but the same error occurs.

Thanks for your reply @kijongGil !

**Comment by kijongGil** [comment] 2018-08-07 00:26
I'm sorry for late reply.
How about your problem?

**Comment by robotpilot** [comment] 2018-08-13 21:48
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Closed** 2018-08-13 21:49 UTC
Labels: question, waiting for reply
